package com.shopstack.common.enums;

public enum OrderStatus {
    PENDING,
    PAYMENT_PENDING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    CONFIRMED,
    PROCESSING,
    PACKING,
    READY_FOR_PICKUP,
    SHIPPED,
    IN_TRANSIT,
    OUT_FOR_DELIVERY,
    DELIVERED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    RETURN_PICKED,
    RETURN_RECEIVED,
    REFUND_INITIATED,
    REFUND_COMPLETED,
    CANCELLED,
    FAILED,
    RETURNED,
    REFUNDED
}