spring.application.name=shopstack-backend
server.port=8080

# MYSQL DATABASE
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/shopstack}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Postgres@123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# FLYWAY
spring.flyway.enabled=false

# MULTIPART FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# JACKSON
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent-output=true

# LOGGING
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# SWAGGER
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
application.security.jwt.secret-key=ReplaceThisWithA256BitSecretKeyForDevelopmentOnly123456789
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# CORS
application.cors.allowed-origins=http://localhost:5173

# FILE STORAGE
application.file.upload-dir=uploads/

# CACHE
spring.cache.type=simple

# ACTUATOR
management.endpoints.web.exposure.include=health,info

# DEVTOOLS
spring.devtools.restart.enabled=true